/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FormComponent {
    }
    interface InputComponent {
        "inputHandler": (e: MouseEvent) => void;
        "label": string;
        "value": string;
    }
    interface SelectComponent {
        "inputHandler": (e: MouseEvent) => void;
        "label": string;
        "value": string;
    }
    interface TabsComponent {
    }
}
declare global {
    interface HTMLFormComponentElement extends Components.FormComponent, HTMLStencilElement {
    }
    var HTMLFormComponentElement: {
        prototype: HTMLFormComponentElement;
        new (): HTMLFormComponentElement;
    };
    interface HTMLInputComponentElement extends Components.InputComponent, HTMLStencilElement {
    }
    var HTMLInputComponentElement: {
        prototype: HTMLInputComponentElement;
        new (): HTMLInputComponentElement;
    };
    interface HTMLSelectComponentElement extends Components.SelectComponent, HTMLStencilElement {
    }
    var HTMLSelectComponentElement: {
        prototype: HTMLSelectComponentElement;
        new (): HTMLSelectComponentElement;
    };
    interface HTMLTabsComponentElement extends Components.TabsComponent, HTMLStencilElement {
    }
    var HTMLTabsComponentElement: {
        prototype: HTMLTabsComponentElement;
        new (): HTMLTabsComponentElement;
    };
    interface HTMLElementTagNameMap {
        "form-component": HTMLFormComponentElement;
        "input-component": HTMLInputComponentElement;
        "select-component": HTMLSelectComponentElement;
        "tabs-component": HTMLTabsComponentElement;
    }
}
declare namespace LocalJSX {
    interface FormComponent {
    }
    interface InputComponent {
        "inputHandler"?: (e: MouseEvent) => void;
        "label"?: string;
        "value"?: string;
    }
    interface SelectComponent {
        "inputHandler"?: (e: MouseEvent) => void;
        "label"?: string;
        "value"?: string;
    }
    interface TabsComponent {
    }
    interface IntrinsicElements {
        "form-component": FormComponent;
        "input-component": InputComponent;
        "select-component": SelectComponent;
        "tabs-component": TabsComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "form-component": LocalJSX.FormComponent & JSXBase.HTMLAttributes<HTMLFormComponentElement>;
            "input-component": LocalJSX.InputComponent & JSXBase.HTMLAttributes<HTMLInputComponentElement>;
            "select-component": LocalJSX.SelectComponent & JSXBase.HTMLAttributes<HTMLSelectComponentElement>;
            "tabs-component": LocalJSX.TabsComponent & JSXBase.HTMLAttributes<HTMLTabsComponentElement>;
        }
    }
}
